### ISSUE TITLE
等系统稳定后的后期需求(2016-4-9前)

### ISSUE THREAD

**Issue by wangxfdu** [zhangweikop/decipherFox#6]
1. 考虑增加一个“练习”页面
   跟正式打码页面类似，区别：
   服务器端准备两三张图片(Xiang提供)，每次随机返回一张；用户提交的结果无需记录。仅做练习使用
2. 主页仅保留名为"练习"和"图片识别"两个链接
   移除其他链接，放到readme里，我们自己测试时可用url直接访问

**Comment by zhangweikop** [comment]
已添加联系页面。

可以将几个练习文件放在practiceFiles下面，当练习时，系统会随机返回practiceFiles这个目录下的文件.
为了好的练习效果，可以多放几个。
